### ISSUE TITLE
User Refactor

### ISSUE THREAD

**Issue by fhtoma** [skni-kod/TournamentAppFrontend#42]
Refactor podstron z userem - w ścieżce url, dla poszczególnego użytkownika unikalny adres (w sensie: /user/id) - analogicznie, jak jest to zrobione dla poszczególnego turnieju.
Poza tym pasuje zrobić porządek w /router/index.ts, bo 2 różne komponenty (inne nazwy) mają taką samą ściężkę.
Uważać na usera niezdefiniowanego w bazie (bez id) - jeśli dla "właściwego" użytkownika nie ma problemu, to ewentualne błędy w konsoli dla ścieżki z /user/undefined ignorować.

**Comment by hekx11** [comment]
dobra 👍
