### ISSUE TITLE
Gallery Fix

### ISSUE THREAD

**Issue by fhtoma** [skni-kod/TournamentAppFrontend#44]
Poprawienie wyświetlania galerii - możliwość przechodzenia na kolejne zdjęcie w trybie powiększonym (przyciski lewo/prawo lub po prostu reagujące na kliknięcie odpowiedniego boku) i ewentualne wyjście z niego po kliknięciu w inne miejsce.
Również dopasowanie zdjęć - obecnie dla nieparzystej ich ilości, zdjęcie zostanie nienaturalnie rozciągnięte.
Kamil wrzucał na SKNIFrontEnd własną wersję galerii, to można "podpatrzeć" ;)

**Comment by Rakso12** [comment]
Skalowanie nieparzystych zdjęć aka logo windowsa, problem występuje przy 1200px

W razie dalszych pytań pytać na kanale projektu.
