### ISSUE TITLE
Navbar Logo + Browser Icon

### ISSUE THREAD

**Issue by fhtoma** [skni-kod/TournamentAppFrontEnd#61]
Stworzenie loga do navbara (1.) i ikonki dla przeglądarki (2.) - obecnie tam jest ikonka z Vue. 
1. Obecnie wykorzystywany jest goniec szachowy, ale chcemy mieć własne logo - próbowałem wykorzystać nasze duże logo, ale nie wygladało za dobrze - jeśli będzie się dało je wkomponować to super, ale chyba trzeba zrobić jakieś dodatkowe.
2. Nie możemy wykorzystać obecnego loga, bo ma format prostokątny (proporcje ~2:1), a jest potrzebny kwadrat (albo do niego zbliżone). Ikonka i tak będzie wykorzystana w niskiej rozdzielczości, więc nie trzeba jakiś dzieł sztuki.

Odnośnie wyglądu, to najlepiej przesyłać propozycje na discordowym kanale projektu.
Najlepiej to robić w jakiś małych wymiarach (np. 300x300), bo nie będzie wykorzystywany jako większy obrazek. Im mniej pamięci zajmie, tym lepiej 😄
Task jest przeznaczony dla grafika, nie webowca 😋

**Comment by nmiarowska** [comment]
kuń zatwierdzony przez Oskara 
![apka_kun_smol](https://user-images.githubusercontent.com/79938114/142758424-540e3f6f-ad1a-4e4f-ae4d-114b181f305a.png)
